apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: opu79t0yy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opu79t0yy-go 
  name: opu79t0yy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: opu79t0yy-go 
